var MONTH_NAMES=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],pluralize=(e,t)=>e+" "+t+(e<=1?"":"s");function getTooltip(e,t){t=new Date(t.getTime()-6e4*t.getTimezoneOffset()).toISOString().split("T")[0];return 0===e.count?"No writing on "+t:pluralize(e.post,"post")+` ${pluralize(e.count,"word")} on `+t}var heatmapTooltip=document.getElementById("heatmap-tooltip");function hideTooltip(){heatmapTooltip.style.display="none"}function tileClickHandler(i){let r=i.target;if(r.classList.contains("tile")){i=new Date(Number(r.dataset.date));let t=i.toISOString();var c=window.REIMU_HEATMAP_CONFIG.articleStats.filter(e=>e.date===t),s=r.dataset.level,i=i.toLocaleDateString();let a=0,l=`
    <div class="tooltip-header">
      <div class="tooltip-header-content">${i} (Level ${s})</div>
      <div class="popup-btn-close tooltip-close"></div>
    </div>
    <div class="tooltip-content">
      <ul>
  `,o=window.REIMU_HEATMAP_CONFIG.i18n,n=document.documentElement.lang||"en";Object.keys(o).includes(n)||(n="en"),0===c.length?l+=`<li>${o[n].no_articles}</li>`:c.forEach(e=>{a+=e.wordcount,l+=`<li><a href="${e.url}">${e.title}</a> (${e.wordcount} ${o[n].words})</li>`});i=o[n].total_articles.replace("$1",c.length).replace("$2",a),s=(l+=`
      </ul>
      <div class="tooltip-footer">
        ${i}
      </div>
    </div>
  `,heatmapTooltip.innerHTML=l,r.getBoundingClientRect()),c=(heatmapTooltip.style.display="block",heatmapTooltip.style.visibility="hidden",heatmapTooltip.style.left="0px",heatmapTooltip.getBoundingClientRect()),i=c.width;let e=s.right+10;e+i>window.innerWidth&&(e=s.left-i-10),heatmapTooltip.style.left=e+"px",heatmapTooltip.style.top=s.top+"px",heatmapTooltip.style.display="block",heatmapTooltip.style.visibility="visible";c=heatmapTooltip.querySelector(".tooltip-close");c&&c.addEventListener("click",hideTooltip),document.addEventListener("click",function e(t){t.target.classList.contains("tile")||heatmapTooltip.contains(t.target)||t.target===r||(hideTooltip(),document.removeEventListener("click",e))})}}function createCalendar(t,e){if(!t)return;t.innerHTML=`
    <div class="outer-box">
      <div class="year-select"></div>
      <div class="inner-box">
        <div class="calendar-container">
          ${["Mon","Wed","Fri"].map(e=>`<span class="week">${e}</span>`).join("")}
          <div class="legend">Less${new Array(5).fill(0).map((e,t)=>`<i class="tile" data-level="${t}"></i>`).join("")}More</div>
          <div class="tiles"></div>
        </div>
      </div>
    </div>
  `;let o=t.querySelector(".calendar-container");var a=t.querySelector(".year-select");let n=t.querySelector(".tiles"),d=completeContributionData(e),l=(new Date).getFullYear(),i=(a.innerHTML=Object.keys(d).sort((e,t)=>t-e).map(e=>`<div class="year-option ${e==l?"active":""}">${e}</div>`).join(""),a.addEventListener("click",({target:e})=>{e.classList.contains("year-option")&&(t.querySelector(".active")?.classList.remove("active"),e.classList.add("active"),i(e.textContent))}),e=>{n.innerHTML="",o.querySelectorAll(".month").forEach(e=>e.remove()),o.querySelectorAll(".total").forEach(e=>e.remove());var t=d[e];let i=new Date(t[0].date).getDay(),r=-1,c=document.createDocumentFragment();var a=document.createDocumentFragment();let s=-1;var[t,l]=t.reduce(([e,t],a,l)=>{var o=new Date(a.date),n=o.getMonth();if(t.count+=a.count,t.post+=a.post,0===o.getDay()&&n!==r){let e=2+Math.floor((l+i)/7);e-s<=1&&(e+=2-e+s),s=e,r=n;l=document.createElement("span");l.className="month",l.textContent=MONTH_NAMES[n],l.style.gridColumn=e,c.append(l)}n=document.createElement("i");return n.className="tile",n.dataset.level=a.level,n.title=getTooltip(a,o),n.dataset.level=a.level,n.dataset.date=a.date,n.addEventListener("click",tileClickHandler),e.push(n),[e,t]},[[],{count:0,post:0}]);t[0]&&(t[0].style.gridRow=i+1),a.append(...t),o.append(c),n.append(a),o.insertAdjacentHTML("beforeend",`<div class="total">${pluralize(l.post,"post")} ${pluralize(l.count,"word")} in ${e}</div>`)});i(l)}function completeContributionData(e){e.sort((e,t)=>e.date-t.date);var t=new Date(e[0].date),a=new Date,l={};let o={};e.forEach(e=>{var t=new Date(e.date),t=`${t.getFullYear()}-${t.getMonth()}-`+t.getDate();o[t]=e});for(let e=t.getFullYear();e<=a.getFullYear();e++){for(var[n,i]=e===a.getFullYear()?[new Date(new Date(a).setDate(a.getDate()-365)),new Date(a.getTime()+864e5)]:[new Date(e,0,1),new Date(e+1,0,1)],r=[],c=n;c<i;c.setDate(c.getDate()+1)){var s=`${c.getFullYear()}-${c.getMonth()}-`+c.getDate();r.push(o[s]||{level:0,date:c.getTime(),count:0,post:0})}l[e]=r}return l}function getLevelFromWordCount(e){var t=window.REIMU_HEATMAP_CONFIG.levelStandard.split(",").map(Number);return e<=0?0:e<=t[0]?1:e<=t[1]?2:e<=t[2]?3:4}var currentDate=new Date;function transformArticlesData(e){e=e.reduce((e,{date:t,wordcount:a})=>{var l;return new Date(t)>currentDate?e:(l=e.get(t)??{count:0,post:0},e.set(t,{count:l.count+a,post:l.post+1}))},new Map);return Array.from(e,([e,{count:t,post:a}])=>({level:getLevelFromWordCount(t),date:new Date(e).getTime(),count:t,post:a}))}createCalendar(document.querySelector("#heatmap"),transformArticlesData(window.REIMU_HEATMAP_CONFIG.articleStats));