(()=>{_$$("pre").forEach(e=>{var o,t=e.parentNode;t.classList.contains("gutter")||((o=document.createElement("div")).className="code-area",t.replaceChild(o,e),o.appendChild(e))});let t=(window.REIMU_CONFIG?.code_block||{}).expand;if(_$$("figure.highlight").forEach(e=>{e.querySelector(".code-figcaption")||e.insertAdjacentHTML("afterbegin",`
  <div class="code-figcaption">
    <div class="code-left-wrap">
      <div class="code-decoration"></div>
      <div class="code-lang"></div>
    </div>
    <div class="code-right-wrap">
      <div class="code-copy icon-copy"></div>
      <div class="icon-chevron-down code-expand"></div>
    </div>
  </div>`),void 0!==t&&(!1===t||"number"==typeof t&&e.querySelectorAll("td.code .line").length>t)&&(e.classList.add("code-closed"),e.style.display="none",e.style.display="");var o=e.className.split(" ")[1];o&&(o=o.replace("line-numbers","").replace("language-","").trim().toUpperCase(),e=e.querySelector(".code-lang"))&&(e.innerText=o)}),_$$(".code-expand").forEach(e=>{e.off("click").on("click",()=>{e.closest("figure")?.classList.toggle("code-closed")})}),window.ClipboardJS){let t=window.REIMU_CONFIG?.clipboard_tips||{},c=(e,o)=>{if("string"==typeof e)return e;if("object"==typeof e){let o=document.documentElement.lang.toLowerCase();var t=Object.keys(e).find(e=>e.toLowerCase()===o);if(t&&e[t])return e[t]}return o},e=new ClipboardJS(".code-copy",{text:e=>{let o=e.parentNode.parentNode.parentNode.querySelector("td.code")?.innerText||"";return t.copyright?.enable&&o.length>=t.copyright?.count&&(o+="\n\n"+(t.copyright?.content??"")),o}});e.on("success",e=>{e.trigger.classList.add("icon-check"),e.trigger.classList.remove("icon-copy");var o=c(t.success,"Copy successfully (*^▽^*)");_$("#copy-tooltip").innerText=o,_$("#copy-tooltip").style.opacity=1,setTimeout(()=>{_$("#copy-tooltip").style.opacity=0,e.trigger.classList.add("icon-copy"),e.trigger.classList.remove("icon-check")},1e3),e.clearSelection()}),e.on("error",e=>{e.trigger.classList.add("icon-times"),e.trigger.classList.remove("icon-copy");var o=c(t.fail,"Copy failed (ﾟ⊿ﾟ)ﾂ");_$("#copy-tooltip").innerText=o,_$("#copy-tooltip").style.opacity=1,setTimeout(()=>{_$("#copy-tooltip").style.opacity=0,e.trigger.classList.add("icon-copy"),e.trigger.classList.remove("icon-times")},1e3)}),window.Pjax&&window.addEventListener("pjax:send",()=>{e.destroy()},{once:!0}),window.AOS?.refresh()}})();